### ISSUE TITLE
Cannot use as a library for multiple cameras

### ISSUE THREAD

**Issue by mitchellwills** [bosch-ros-pkg/usb_cam#29]
Currently is is difficult to use this as a library to communicate with multiple cameras in the same node because of global state. It would be nice if usb_cam.cpp was refactored to move all of the state into a class.

I would be happy to offer a pull request if it would be accepted.

**Comment by rctoris** [comment]
:+1: I like it!

**Comment by mitchellwills** [comment]
Should I leave the original API as well for backwards compatibility?

**Comment by rctoris** [comment]
We can remove it and just do a major version tick.

**Comment by rctoris** [comment]
Also, since the headers are installed incorrectly, I doubt anyone is use it outside of usb_cam.
